controllers/proyectos_controller.py
from flask import request,redirect,url_for,Blueprint
from datetime import datetime
from models.proyectos_model import Proyecto
from models.usuario_model import Usuario
from models.factura_model import Factura
from views import proyecto_view

proyecto_bp=Blueprint('proyecto',__name__,url_prefix='/proyectos')

@proyecto_bp.route('/')
def index():
    # recupera todo los registros de proyectos
    cont_p=Proyecto.query.count()
    cont_pryent=Proyecto.query.filter_by(estado = 'Entregado').count()
    porp= (cont_pryent * 100)/cont_p
    porp=round(porp,2)
    cont_usr = Usuario.query.count()
    cont_usup=Usuario.query.filter_by(id_rol = 3).count()
    porus=(cont_usup * 100)/cont_usr
    porus=round(porus,2)
    tsals = Factura.query.filter_by(deuda='cancelado').count()
    tot=Factura.query.count()
    pors = (tsals * 100)/tot
    porsl=round(pors,2)
    # estds=(cont_p,porp,cont_usr,porus,total_sal,porsl)
    proyectos= Proyecto.get_all()
    usuarios = Usuario.get_all()
    facturas = Factura.get_all()
    return proyecto_view.list(proyectos,usuarios,facturas,cont_p,porp,cont_usr,porus,tot,porsl)

@proyecto_bp.route('/detalle')
def detalles():
    # recupera todo los registros de proyectos
    proyectos= Proyecto.get_all()
    return proyecto_view.detalles(proyectos)

@proyecto_bp.route('/create',methods=['GET','POST'])
def create():
    if request.method == 'POST':
        proyecto=request.form['proyecto']
        caracteristica=request.form['caracteristica']
        superficie=request.form['superficie']
        ubicacion=request.form['ubicacion']
        imagen=request.form['imagen']
        fechain_str=request.form['fecha_inicio']
        fechafn_str=request.form['fecha_fin']
        if fechafn_str:
            fechafin=fechafn_str
        else:
            fechafin=fechain_str
        estado=request.form['estado']
        presupuesto=request.form['presupuesto']
        id_usuario=request.form['id_usuario']

        fecha_inicio = datetime.strptime(fechain_str,'%Y-%m-%d').date()
        fecha_fin = datetime.strptime(fechafin,'%Y-%m-%d').date()

        proyectos = Proyecto(proyecto,caracteristica,superficie,ubicacion,imagen,fecha_inicio,fecha_fin,estado,presupuesto,id_usuario)
        proyectos.save()
        return redirect(url_for('proyecto.index'))

    usuarios = Usuario.query.filter_by(id_rol=3)
    return proyecto_view.create(usuarios)

@proyecto_bp.route('/edit/<int:id>',methods=['GET','POST'])
def edit(id):
    proyects= Proyecto.get_by_id(id)
    if request.method=='POST':
        proyecto=request.form['proyecto']
        caracteristica=request.form['caracteristica']
        superficie=request.form['superficie']
        ubicacion=request.form['ubicacion']
        imagen=request.form['imagen']
        fechain_str=request.form['fecha_inicio']
        fechafn_str=request.form['fecha_fin']
        estado=request.form['estado']
        presupuesto=request.form['presupuesto']
        id_usuario=request.form['id_usuario']

        fecha_inicio = datetime.strptime(fechafn_str,'%Y-%m-%d').date()
        fecha_fin = datetime.strptime(fechain_str,'%Y-%m-%d').date()

        # actualizar
        proyects.update(proyecto=proyecto,caracteristica=caracteristica,superfice=superficie,ubicacion=ubicacion,imagen=imagen,fecha_inicio=fecha_inicio,fecha_fin=fecha_fin,estado=estado,presupuesto=presupuesto,id_usuario=id_usuario)
        return redirect(url_for('proyecto.index'))
    
    usuarios=Usuario.query.filter_by(id_rol=3)
    return proyecto_view.edit(proyects,usuarios)

@proyecto_bp.route('/delete/<int:id>')
def delete(id):
    proyecto=Proyecto.get_by_id(id)
    proyecto.delete()
    return redirect(url_for('proyecto.index'))

views/proyecto_view.py
from flask import render_template

def list(proyectos,usuarios,facturas,cont_p,porp,cont_usr,porus,total_sal,porsl):
    return render_template('proyectos/index.html',proyectos=proyectos,usuarios=usuarios,facturas=facturas,cont_p=cont_p,porp=porp,cont_usr=cont_usr,porus=porus,total_sal=total_sal,porsl=porsl)

def create(usuarios):
    # se requiere productos y usuarios
    return render_template('proyectos/create.html',usuarios=usuarios)

def edit(proyects,usuarios):
    # se requiere proyectos y usuarios
    return render_template('proyectos/edit.html',proyects=proyects,usuarios=usuarios)

def detalles(proyectos):
    # se requiere proyectos
    return render_template('proyectos/detalles.html',proyectos=proyectos)

templates/proyectos/create.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Registrar Proyecto {% endblock %}

{% block content %}
<section class="section">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <img class="d-flex justify-content-center text-center py-4" src="{{url_for('static',filename='img/logot.png')}}" alt="" width="200">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Registrar Nuevo proyecto</h5>

                <!-- Multi Columns Form -->
                <form class="row g-3" method="POST" action="{{ url_for('proyecto.create') }}">
                <div class="col-md-12">
                    <label for="" class="form-label">Proyecto</label>
                    <input type="text" class="form-control" name="proyecto" required>
                </div>
                <div class="col-md-12">
                    <label for="" class="form-label">Caracteristica</label>
                    <input type="text" class="form-control" name="caracteristica"required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Superficie</label>
                    <input type="number" class="form-control" name="superficie">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Ubicacion</label>
                    <input type="text" class="form-control" name="ubicacion" placeholder="Departamento, Municipio, Distrito" required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Imagen</label>
                    <input type="file" class="form-control" name="imagen">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Fecha de contrato</label>
                    <input type="date" class="form-control" name="fecha_inicio" required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Fecha de entrega</label>
                    <input type="date" class="form-control" name="fecha_fin">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Estado</label>
                    <select name="estado" class="form-select" required>
                        <option selected="">Seleccionar</option>
                        <option value="En Proceso">En Proceso</option>
                        <option value="En Construsccion">En Construccion</option>
                        <option value="Entregado">Entregado</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Presupuesto</label>
                    <input type="number" class="form-control" name="presupuesto" min="0" step="0.01">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Usuario</label>
                    <select name="id_usuario" id="" class="form-control" required>
                        <option value="">Seleccionar un supervisor</option>
                        {% for usuario in usuarios %}
                        <option value="{{usuario.id}}">{{ usuario.nombre }} {{usuario.apellido}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-warning">Registrar</button>
                </div>
                </form><!-- End Multi Columns Form -->

            </div>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
  </section>
{% endblock %}

templates/proyectos/detalles.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Proyectos | Detalle {% endblock %}

{% block content %}
<div class="pagetitle">
    <h1>Proyectos</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/proyectos">Proyectos</a></li>
        <li class="breadcrumb-item">Tables</li>
        <li class="breadcrumb-item active">Data</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      <div class="col-lg-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Detalle de los proyectos</h5>
                <!-- Table with stripped rows -->
                <table class="table datatable">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Proyecto</th>
                        <th>Caracteristica</th>
                        <th>Superficie</th> 
                        <th>Ubicacion</th>
                        <th>Fecha de Inicio</th>
                        <th>Fecha de Entrega</th>
                        <th>Estado</th>
                        <th>Presupuesto</th>
                        <th>Supervisor</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in proyectos %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <td>{{ item.proyecto }}</td>
                        <td>{{ item.caracteristica }}</td>
                        <td>{{ item.superfice }} m&sup2</td>
                        <td>{{ item.ubicacion }}</td>
                        <td>{{ item.fecha_inicio.strftime('%d/%m/%Y') }}</td>
                        <td>{{ item.fecha_fin.strftime('%d/%m/%Y') }}</td>
                        <td>{{ item.estado }}</td>
                        <td>{{ item.presupuesto}}</td>
                        <td>{{ item.usuario.nombre }} {{item.usuario.apellido }}</td>
                        <td>
                        <a href="{{ url_for('proyecto.edit',id=item.id) }}" class="btn btn-outline-warning"><i class="bi bi-pencil-square"></i></a>
                        </td>
                        <td>
                        <a href="{{ url_for('proyecto.delete',id=item.id) }}" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <!-- End Table with stripped rows -->

            </div>
        </div>

      </div>
    </div>
  </section>
{% endblock %}

templates/proyectos/edit.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Editar Proyecto {% endblock %}

{% block content %}
<section class="section">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <img class="d-flex justify-content-center text-center py-4" src="{{url_for('static',filename='img/logot.png')}}" alt="" width="200">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Editar proyecto</h5>

                <!-- Multi Columns Form -->
                <form class="row g-3" method="POST" action="{{ url_for('proyecto.edit',id=proyects.id) }}">
                <div class="col-md-12">
                    <label for="" class="form-label">Proyecto</label>
                    <input type="text" class="form-control" name="proyecto" value="{{ proyects.proyecto }}" required>
                </div>
                <div class="col-md-12">
                    <label for="" class="form-label">Caracteristica</label>
                    <input type="text" class="form-control" name="caracteristica" value="{{ proyects.caracteristica }}" required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Superficie /m <sup>2</sup></label>
                    <input type="number" class="form-control" name="superficie" value="{{ proyects.superfice }}">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Ubicacion</label>
                    <input type="text" class="form-control" name="ubicacion" value="{{ proyects.ubicacion }}" placeholder="Departamento, Municipio, Distrito" required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Imagen</label>
                    <input type="file" class="form-control" value="{{ proyects.imagen }}" name="imagen">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Fecha de contrato</label>
                    <input type="date" class="form-control" name="fecha_inicio" value="{{ proyects.fecha_inicio.strftime('%Y-%m-%d') }}" required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Fecha de entrega</label>
                    <input type="date" class="form-control" name="fecha_fin" value="{{ proyects.fecha_fin.strftime('%Y-%m-%d') }}">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Estado {{ proyects.estado }}</label>
                    <select  class="form-select" name="estado" required>
                        <option selected="">Seleccionar</option>
                        <option value="En Proceso">En Proceso</option>
                        <option value="En Construsccion">En Construccion</option>
                        <option value="Entregado">Entregado</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Presupuesto</label>
                    <input type="number" class="form-control" value="{{ proyects.presupuesto }}" name="presupuesto" min="0" step="0.01">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Usuario</label>
                    <select name="id_usuario" id="" class="form-control" required>
                        <option value="">Seleccionar un supervisor</option>
                        {% for usuario in usuarios %}
                        <option value="{{usuario.id}}" {% if usuario.id== proyects.usuario_id %} selected {% endif %}>{{ usuario.nombre }} {{usuario.apellido}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-warning">Guardar</button>
                </div>
                </form><!-- End Multi Columns Form -->

            </div>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
  </section>
{% endblock %}

templates/proyectos/index.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Proyectos {% endblock %}

{% block content %}
<div class="pagetitle">
    <h1>Proyectos</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/proyectos">Admin</a></li>
        <li class="breadcrumb-item active">Proyectos</li>
      </ol>
    </nav>
</div><!-- End Page Title -->

<section class="section dashboard">
    <div class="row">

      <!-- Left side columns -->
      <div class="col-lg-12">
        <div class="row">

          <!-- Sales Card -->
          <div class="col-xxl-4 col-md-6">
            <div class="card info-card sales-card">

              <div class="card-body">
                <h5 class="card-title">Proyectos <span>| Entrgas</span></h5>

                <div class="d-flex align-items-center">
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                    <i class="ri-folder-5-line"></i>
                  </div>
                  <div class="ps-3">
                    <h6>{{ cont_p }}</h6>
                    <span class="text-success small pt-1 fw-bold">{{porp}} %</span> <span class="text-muted small pt-2 ps-1">Entregados</span>

                  </div>
                </div>
              </div>

            </div>
          </div><!-- End Sales Card -->

          <!-- Revenue Card -->
          <div class="col-xxl-4 col-md-6">
            <div class="card info-card revenue-card">

              <div class="card-body">
                <h5 class="card-title">Facturas <span>| canceladas</span></h5>

                <div class="d-flex align-items-center">
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                    <i class="bi bi-currency-dollar"></i>
                  </div>
                  <div class="ps-3">
                    <h6>{{total_sal}}</h6>
                    <span class="text-success small pt-1 fw-bold">{{porsl}} %</span> <span class="text-muted small pt-2 ps-1">Canceladas</span>

                  </div>
                </div>
              </div>

            </div>
          </div><!-- End Revenue Card -->

          <!-- Customers Card -->
          <div class="col-xxl-4 col-xl-12">

            <div class="card info-card customers-card">

              <div class="card-body">
                <h5 class="card-title">Personal <span>| Administrativo</span></h5>

                <div class="d-flex align-items-center">
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                    <i class="bi bi-people"></i>
                  </div>
                  <div class="ps-3">
                    <h6>{{cont_usr}} </h6>
                    <span class="text-danger small pt-1 fw-bold">{{porus}} %</span> <span class="text-muted small pt-2 ps-1">Supervisores</span>

                  </div>
                </div>

              </div>
            </div>

          </div><!-- End Customers Card -->

        <!-- Recent Sales -->
          <div class="col-12">
            <div class="card recent-sales overflow-auto">

              <div class="card-body">
                <h5 class="card-title">Proyectos <span>| </span></h5>

                <table class="table table-borderless datatable">
                  <thead>
                    <tr>
                        <th scope="col" >Id</th>
                        <th scope="col">Proyecto</th>
                        <th scope="col">Supervisor</th>
                        <th scope="col">Caracteristica</th>
                        <th scope="col">Ubicacion</th>
                        <th scope="col">Estado</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in proyectos %}
                    <tr>
                        <th class="fw-bold"><a href="{{ url_for('proyecto.edit',id=item.id) }}">{{ item.id }}</a></th>
                        <th>{{ item.proyecto }}</th>
                        <th>{{ item.usuario.nombre }} {{item.usuario.apellido }}</th>
                        <th>{{ item.caracteristica }}</th>
                        <th>{{ item.ubicacion }}</th>
                        <th class="badge 
                            {{ 'bg-danger' if item.estado == 'En Proceso' else '' }} 
                            {{ 'bg-warning' if item.estado == 'En Construsccion' else '' }} 
                            {{ 'bg-success' if item.estado == 'Entregado' else '' }}">
                            {{ item.estado }}
                        </th>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>

              </div>

            </div>
          </div><!-- End Recent Sales -->

          <!-- Top Selling -->
          <div class="col-12">
            <div class="card top-selling overflow-auto">

              <div class="card-body pb-0">
                <h5 class="card-title">Facturas <span>| lista</span></h5>

                <table class="table table-borderless">
                  <thead>
                    <tr>
                      <th scope="col">Id</th>
                      <th scope="col">Nro de Proyecto</th>
                      <th scope="col">Nro Factura</th> 
                      <th scope="col">Concepto</th>
                      <th scope="col">Importe total</th>
                      <th scope="col">Cuentas</th>
                      <th scope="col">Saldo</th>
                      <th scope="col">Deuda</th>
                      <th scope="col">Fecha</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for item in facturas %}
                    <tr>
                        <th class="fw-bold">{{ item.id }}</th>
                        <td>{{ item.id_proyecto }}</td>
                        <td>{{ item.nro_factura }}</td>
                        <td>{{ item.concepto }}</td>
                        <td>Bs {{ item.monto }}</td>
                        <td>Bs {{ item.cuenta }}</td>
                        <td>Bs {{ item.saldo}}</td>
                        <td class="badge 
                            {{ 'bg-danger' if item.deuda == 'nuevo' else '' }} 
                            {{ 'bg-warning' if item.deuda == 'saldo' else '' }} 
                            {{ 'bg-success' if item.deuda == 'cancelado' else '' }}">
                            {{ item.deuda }}
                        </td>
                        <td>{{ item.fecha.strftime('%d/%m/%Y')}}</td>
                    </tr>
                    {% endfor %}
                    
                  </tbody>
                </table>
              </div>
            </div>
          </div><!-- End Top Selling -->
        </div>
      </div><!-- End Left side columns -->
    </div>
  </section>

{% endblock %}