controllers/usuarios_controller.py
from flask import request,redirect,url_for,Blueprint,session
from datetime import datetime
from models.usuario_model import Usuario
from models.profesion_model import Profesion
from models.rol_model import Rol
from views import usuario_view
from functools import wraps

usuario_bp=Blueprint('usuario',__name__,url_prefix='/usuarios')

@usuario_bp.route('/')
def index():
    # recupera todo los registros de usuarios
    usuarios = Usuario.query.all()
    profesions =Profesion.query.all()
    return usuario_view.list(usuarios,profesions)

@usuario_bp.route('/create',methods=['GET','POST'])
def create():
    if request.method == 'POST':
        nombre=request.form['nombre']
        apellido=request.form['apellido']
        foto_f=request.form['foto']
        if foto_f:
            foto=foto_f
        else:
            foto='defaul.jpg'
        telefono=request.form['telefono']
        salario=request.form['salario']
        obs='s/n'
        id_profesion=request.form['profesion_id']
        id_rol = 5

        usuarios = Usuario(nombre,apellido,foto,telefono,salario,obs,id_profesion,id_rol)
        usuarios.save()
        return redirect(url_for('usuario.index'))

    profesiones = Profesion.get_all()
    return usuario_view.create(profesiones)

@usuario_bp.route('/edit/<int:id>',methods=['GET','POST'])
def edit(id):
    usuario= Usuario.get_by_id(id)
    if request.method=='POST':
        nombre=request.form['nombre']
        apellido=request.form['apellido']
        foto=request.form['foto']
        telefono=request.form['telefono']
        salario=request.form['salario']
        obs=request.form['obs']
        id_profesion=request.form['id_profesion']
        id_rol=request.form['id_rol']

        # actualizar
        usuario.update(nombre=nombre,apellido=apellido,foto=foto,telefono=telefono,salario=salario,obs=obs,id_profesion=id_profesion,id_rol=id_rol)
        return redirect(url_for('usuario.index'))
    
    profesiones = Profesion.get_all()
    roles = Rol.get_all()
    return usuario_view.edit(usuario,profesiones,roles)

@usuario_bp.route('/delete/<int:id>')
def delete(id):
    usuario=Usuario.get_by_id(id)
    usuario.delete()
    return redirect(url_for('usuario.index'))

@usuario_bp.route('/user_profile/<int:id>',methods=['GET','POST'])
def user_profile(id):
    usuario= Usuario.get_by_id(id)
    if request.method=='POST':
        nombre=request.form['nombre']
        apellido=request.form['apellido']
        foto=request.form['foto']
        telefono=request.form['telefono']
        salario=request.form['salario']
        obs=request.form['obs']
        id_profesion=request.form['id_profesion']
        id_rol=request.form['id_rol']

        # actualizar
        usuario.update(nombre=nombre,apellido=apellido,foto=foto,telefono=telefono,salario=salario,obs=obs,id_profesion=id_profesion,id_rol=id_rol)
        return redirect(url_for('usuario.index'))
    
    profesiones = Profesion.get_all()
    roles = Rol.get_all()
    return usuario_view.user_profile(usuario,profesiones,roles)

views/usuario_view.py
from flask import render_template

def list(usuarios,profesion):
    return render_template('usuarios/index.html',usuarios=usuarios,profesion=profesion)

def create(profesiones):
    # se requiere profesiones
    return render_template('usuarios/create.html',profesiones=profesiones)

def edit(usuario,profesiones,roles):
    # se requiere profesiones y usuarios
    return render_template('usuarios/edit.html',usuario=usuario,profesiones=profesiones,roles=roles)

def user_profile(usuario,profesiones,roles):
    return render_template('usuarios/user_profile.html',usuario=usuario,profesiones=profesiones,roles=roles)

templates/usuarios/create.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Registrar Usuario {% endblock %}

{% block content %}
<section class="section">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <img class="d-flex justify-content-center text-center py-4" src="{{url_for('static',filename='img/logot.png')}}" alt="" width="200">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Registrar Nuevo Usuario</h5>

                <!-- Multi Columns Form -->
                <form class="row g-3" method="POST" action="{{ url_for('usuario.create') }}">
                <div class="col-md-12">
                    <label for="" class="form-label">Nombre</label>
                    <input type="text" class="form-control" name="nombre" required>
                </div>
                <div class="col-md-12">
                    <label for="" class="form-label">Apellido</label>
                    <input type="text" class="form-control" name="apellido"required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Imagen</label>
                    <input type="file" class="form-control" name="foto">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Telefono</label>
                    <input type="number" class="form-control" name="telefono">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Salario</label>
                    <input type="number" class="form-control" name="salario" min="0" step="0.01" required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Profesion</label>
                    <select name="profesion_id" id="" class="form-control" required>
                        <option value="">Seleccionar una profesion</option>
                        {% for item in profesiones %}
                        <option value="{{ item.id }}">{{ item.profesion }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-warning">Registrar</button>
                </div>
                </form><!-- End Multi Columns Form -->

            </div>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
  </section>
{% endblock %}

templates/usuarios/edit.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Editar Usuario {% endblock %}

{% block content %}
<section class="section">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <img class="d-flex justify-content-center text-center py-4" src="{{url_for('static',filename='img/logot.png')}}" alt="" width="200">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Editar Usuario</h5>

                <!-- Multi Columns Form -->
                <form class="row g-3" method="POST" action="{{ url_for('usuario.edit',id=usuario.id) }}">
                <div class="col-md-12">
                    <label for="" class="form-label">Nombre</label>
                    <input type="text" class="form-control" name="nombre" value="{{ usuario.nombre }}" required>
                </div>
                <div class="col-md-12">
                    <label for="" class="form-label">Apellido</label>
                    <input type="text" class="form-control" value="{{ usuario.apellido }}" name="apellido"required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Imagen</label>
                    <input type="file" class="form-control" value="{{ usuario.foto }}" name="foto">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Telefono</label>
                    <input type="number" class="form-control" value="{{ usuario.telefono }}" name="telefono">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Salario</label>
                    <input type="number" class="form-control" value="{{ usuario.salario }}" name="salario" min="0" step="0.01" required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Observaciones</label>
                    <textarea name="obs" id="" class="form-control" aria-valuetext="{{ usuario.obs }}"></textarea>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Profesion</label>
                    <select name="id_profesion"  class="form-control" required>
                        <option value="">Seleccionar una profesion</option>
                        {% for item in profesiones %}
                        <option value="{{ item.id }}" {% if item.id == usuario.id_profesion %} selected {% endif %}>{{ item.profesion }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Rol</label>
                    <select name="id_rol" id="" class="form-control" required>
                        <option value="">Seleccionar un rol</option>
                        {% for rol in roles %}
                        <option value="{{ rol.id }}" {% if rol.id== usuario.id_rol %} selected {% endif %}>{{ rol.cargo }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-warning">Registrar</button>
                </div>
                </form><!-- End Multi Columns Form -->

            </div>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
  </section>
{% endblock %}

templates/usuarios/index.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Usuarios {% endblock %}

{% block content %}
<div class="pagetitle">
    <h1>Usuarios</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/usuarios">Usuarios</a></li>
        <li class="breadcrumb-item">Tables</li>
        <li class="breadcrumb-item active">Data</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      <div class="col-lg-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Lista de Usuarios</h5>
                <!-- Table with stripped rows -->
                <table class="table datatable">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Perfil</th> 
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Profesion</th>
                        <th>Rol</th>
                        <th>Telefono</th>
                        <th>Salario</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in usuarios %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <th scope="row"><a href="{{ url_for('usuario.user_profile',id=item.id) }}"><img src="../../static/img/team/{{ item.foto }}" alt="" width="30" class="rounded-circle"></a></th>
                        <td>{{ item.nombre }}</td>
                        <td>{{ item.apellido }}</td>
                        <td>{{ item.profesions.profesion }}</td>
                        <td>{{ item.rols.cargo }}</td>
                        <td>{{ item.telefono }}</td>
                        <td>{{ item.salario}}</td>
                        <td>
                        <a href="{{ url_for('usuario.edit',id=item.id) }}" class="btn btn-outline-warning"><i class="bi bi-pencil-square"></i></a>
                        </td>
                        <td>
                        <a href="{{ url_for('usuario.delete',id=item.id) }}" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <!-- End Table with stripped rows -->

            </div>
        </div>

      </div>
    </div>
  </section>
{% endblock %}

templates/usuarios/user_profile.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Usuarios {% endblock %}

{% block content %}
    <div class="pagetitle">
      <h1>Profile</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item">Users</li>
          <li class="breadcrumb-item active">Profile</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section profile">
      <div class="row">
        <div class="col-xl-4">

          <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

              <img src="../../static/img/team/{{ usuario.foto}}" alt="Profile" class="rounded-circle">
              <h2>{{ usuario.nombre }} {{ usuario.apellido }}</h2>
              <h3>{{ usuario.profesions.profesion }}</h3>
              <div class="social-links mt-2">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>

        </div>

        <div class="col-xl-8">

          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Detalles</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Editar Perfil</button>
                </li>

              </ul>
              <div class="tab-content pt-2">

                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                  <h5 class="card-title">Detalles de Perfil</h5>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Nombre</div>
                    <div class="col-lg-9 col-md-8">{{ usuario.nombre }}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Apellido</div>
                    <div class="col-lg-9 col-md-8">{{ usuario.apellido }}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Profesion</div>
                    <div class="col-lg-9 col-md-8">{{ usuario.profesions.profesion }}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Cargo</div>
                    <div class="col-lg-9 col-md-8">{{ usuario.rols.cargo }}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Telefono</div>
                    <div class="col-lg-9 col-md-8">{{ usuario.telefono }}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Salario</div>
                    <div class="col-lg-9 col-md-8">{{ usuario.salario }}</div>
                  </div>

                </div>

                <div class="tab-pane fade profile-edit pt-3" id="profile-edit">

                  <!-- Profile Edit Form -->
                  <form action="{{ url_for('usuario.edit',id=usuario.id) }}">
                    <div class="row mb-3">
                      <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label>
                      <div class="col-md-8 col-lg-9">
                        <img src="../../static/img/team/{{ usuario.foto}}" alt="Profile">
                        <div class="pt-2">
                          <a href="#" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-upload"></i></a>
                          <a href="#" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>
                        </div>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="nombre" class="col-md-4 col-lg-3 col-form-label">Nombre</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="nombre" type="text" class="form-control" id="nombre" value="{{ usuario.nombre}}">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="apellido" class="col-md-4 col-lg-3 col-form-label">apellido</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="apellido" type="text" class="form-control" id="apellido" value="{{ usuario.apellido}}">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="profesion" class="col-md-4 col-lg-3 col-form-label">Profesion</label>
                      <div class="col-md-8 col-lg-9">
                        <select name="id_profesion"  class="form-control" required id="profesion">
                            <option value="">Seleccionar una profesion</option>
                            {% for item in profesiones %}
                            <option value="{{ item.id }}" {% if item.id == usuario.id_profesion %} selected {% endif %}>{{ item.profesion }}</option>
                            {% endfor %}
                        </select>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="cargo" class="col-md-4 col-lg-3 col-form-label">Cargo</label>
                      <div class="col-md-8 col-lg-9">
                        <select name="id_rol" id="" class="form-control" required id="cargo">
                            <option value="">Seleccionar un rol</option>
                            {% for rol in roles %}
                            <option value="{{ rol.id }}" {% if rol.id== usuario.id_rol %} selected {% endif %}>{{ rol.cargo }}</option>
                            {% endfor %}
                        </select>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="telefono" class="col-md-4 col-lg-3 col-form-label">Telefono</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="telefono" type="text" class="form-control" id="telefono" value="{{ usuario.telefono}}">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="salario" class="col-md-4 col-lg-3 col-form-label">Sueldo</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="salario" type="number" class="form-control" id="salario" value="{{ usuario.salario}}">
                      </div>
                    </div>

                    <div class="row mb-3">
                        <label for="obs" class="col-md-4 col-lg-3 col-form-label">Observaciones</label>
                        <div class="col-md-8 col-lg-9">
                          <textarea name="obs" class="form-control" id="obs" style="height: 100px" aria-valuetext="{{ usuario.obs }}"></textarea>
                        </div>
                    </div>

                    <!-- <div class="row mb-3">
                      <label for="Linkedin" class="col-md-4 col-lg-3 col-form-label">Linkedin Profile</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="linkedin" type="text" class="form-control" id="Linkedin" value="https://linkedin.com/#">
                      </div>
                    </div> -->

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Guardar cambios</button>
                    </div>
                  </form><!-- End Profile Edit Form -->

                </div>

              </div><!-- End Bordered Tabs -->

            </div>
          </div>

        </div>
      </div>
    </section>

{% endblock %}