controllers/facturas_controller.py
from flask import request,redirect,url_for,Blueprint
from datetime import datetime
from models.proyectos_model import Proyecto
from models.factura_model import Factura
from views import factura_view
from decimal import Decimal

factura_bp=Blueprint('factura',__name__,url_prefix='/facturas')

@factura_bp.route('/')
def index():
    # recupera todo los registros de facturas
    facturas = Factura.query.all()
    projects =Proyecto.query.all()
    return factura_view.list(facturas,projects)

@factura_bp.route('/create',methods=['GET','POST'])
def create():
    if request.method == 'POST':
        id_proyecto=request.form['id_proyecto']
        nro_factura=request.form['nro_factura']
        concepto=request.form['concepto']
        monto=request.form['monto']
        cuenta=request.form['cuenta']
        saldo=int(monto)-int(cuenta)
        fecha = datetime.now().date()
        
        if saldo == 0:
            deuda = 'cancelado'

        if saldo == int(monto):
            deuda = 'nuevo'

        if saldo >0 and saldo < int(monto):
            deuda= 'saldo'
        
        facturas = Factura(id_proyecto=id_proyecto,nro_factura=nro_factura,concepto=concepto,monto=monto,cuenta=cuenta,saldo=saldo,deuda=deuda,fecha=fecha)
        facturas.save()
        return redirect(url_for('factura.index'))

    projects = Proyecto.query.all()
    return factura_view.create(projects)

@factura_bp.route('/edit/<int:id>',methods=['GET','POST'])
def edit(id):
    factura = Factura.get_by_id(id)
    if request.method=='POST':
        id_proyecto=request.form['id_proyecto']
        nro_factura=request.form['nro_factura']
        concepto=request.form['concepto']
        saldop=request.form['saldo']
        monto =factura.monto
        cuenta=monto
        saldo='0.0'
        fecha = datetime.now().date()
        deuda = 'cancelado'
        # actualizar
        factura.update(id_proyecto=id_proyecto,nro_factura=nro_factura,concepto=concepto,monto=monto,cuenta=cuenta,saldo=saldo,deuda=deuda,fecha=fecha)
        return redirect(url_for('factura.index'))
    
    projects = Proyecto.get_all()
    return factura_view.edit(factura,projects)

@factura_bp.route('/delete/<int:id>')
def delete(id):
    factura=factura.get_by_id(id)
    factura.delete()
    return redirect(url_for('factura.index'))

controllers/login_controller.py
from flask import request,redirect,url_for,Blueprint,session,flash
from werkzeug.security import generate_password_hash, check_password_hash
from models.usuario_model import Usuario
from models.proyectos_model import Proyecto
from models.user_model import User
from views import login_view,welcome_view,proyecto_view

login_bp=Blueprint('login',__name__,url_prefix='/login')

@login_bp.route('/',methods=['GET','POST'])
def index():
    if request.method=='POST':
        username=request.form['username']
        password=request.form['password']
        
        users = User.query.filter_by(username=username).first()
        if users and check_password_hash(users.password,password):
            idus=users.id_usuario
            session['user_log'] = idus
            return redirect('/proyectos/')
        else:
            flash("Usuario o contraseña incorrectos.")  
    return login_view.inicio()

@login_bp.route('/create',methods=['GET','POST'])
def create():
    if request.method == 'POST':
        username=request.form['username']
        password=request.form['password']
        id_usuario=request.form['id_usuario']

        user = User(username,password,id_usuario)
        user.save()
        return  redirect('/proyectos/')
    usuuarios=Usuario.get_all()
    return login_view.create(usuuarios)

@login_bp.route('/vaciar',methods=['GET'])
def vaciar():
    # elimina de session user_log
    session.pop("user_log",None)
    return welcome_view.inicio()

controllers/usuarios_controller.py
from flask import request,redirect,url_for,Blueprint,session
from datetime import datetime
from models.usuario_model import Usuario
from models.profesion_model import Profesion
from models.rol_model import Rol
from views import usuario_view
from functools import wraps

usuario_bp=Blueprint('usuario',__name__,url_prefix='/usuarios')

@usuario_bp.route('/')
def index():
    # recupera todo los registros de usuarios
    usuarios = Usuario.query.all()
    profesions =Profesion.query.all()
    return usuario_view.list(usuarios,profesions)

@usuario_bp.route('/create',methods=['GET','POST'])
def create():
    if request.method == 'POST':
        nombre=request.form['nombre']
        apellido=request.form['apellido']
        foto_f=request.form['foto']
        if foto_f:
            foto=foto_f
        else:
            foto='defaul.jpg'
        telefono=request.form['telefono']
        salario=request.form['salario']
        obs='s/n'
        id_profesion=request.form['profesion_id']
        id_rol = 5

        usuarios = Usuario(nombre,apellido,foto,telefono,salario,obs,id_profesion,id_rol)
        usuarios.save()
        return redirect(url_for('usuario.index'))

    profesiones = Profesion.get_all()
    return usuario_view.create(profesiones)

@usuario_bp.route('/edit/<int:id>',methods=['GET','POST'])
def edit(id):
    usuario= Usuario.get_by_id(id)
    if request.method=='POST':
        nombre=request.form['nombre']
        apellido=request.form['apellido']
        foto=request.form['foto']
        telefono=request.form['telefono']
        salario=request.form['salario']
        obs=request.form['obs']
        id_profesion=request.form['id_profesion']
        id_rol=request.form['id_rol']

        # actualizar
        usuario.update(nombre=nombre,apellido=apellido,foto=foto,telefono=telefono,salario=salario,obs=obs,id_profesion=id_profesion,id_rol=id_rol)
        return redirect(url_for('usuario.index'))
    
    profesiones = Profesion.get_all()
    roles = Rol.get_all()
    return usuario_view.edit(usuario,profesiones,roles)

@usuario_bp.route('/delete/<int:id>')
def delete(id):
    usuario=Usuario.get_by_id(id)
    usuario.delete()
    return redirect(url_for('usuario.index'))

@usuario_bp.route('/user_profile/<int:id>',methods=['GET','POST'])
def user_profile(id):
    usuario= Usuario.get_by_id(id)
    if request.method=='POST':
        nombre=request.form['nombre']
        apellido=request.form['apellido']
        foto=request.form['foto']
        telefono=request.form['telefono']
        salario=request.form['salario']
        obs=request.form['obs']
        id_profesion=request.form['id_profesion']
        id_rol=request.form['id_rol']

        # actualizar
        usuario.update(nombre=nombre,apellido=apellido,foto=foto,telefono=telefono,salario=salario,obs=obs,id_profesion=id_profesion,id_rol=id_rol)
        return redirect(url_for('usuario.index'))
    
    profesiones = Profesion.get_all()
    roles = Rol.get_all()
    return usuario_view.user_profile(usuario,profesiones,roles)

controllers/welcome_controller.py
from flask import request,redirect,url_for,Blueprint
from models.rol_model import Rol
from models.profesion_model import Profesion
from models.usuario_model import Usuario
from models.proyectos_model import Proyecto
from views import welcome_view

welcome_bp=Blueprint('inicio',__name__,url_prefix='/inicio')

@welcome_bp.route('/')
def index():
    return welcome_view.inicio()

@welcome_bp.route('/nosotros')
def nosotros():
    # recuperrar registros
    roles=Rol.get_all()
    profesion=Profesion.get_all()
    usuarios=Usuario.get_rol()
    return welcome_view.nosotros(roles,profesion,usuarios)

@welcome_bp.route('/servicios')
def servicios():
    proyectos=Proyecto.get_all()
    return welcome_view.servicios(proyectos)

@welcome_bp.route('/proyectos')
def proyectos():
    proyectos=Proyecto.get_all()
    usuarios=Usuario.get_all()
    profession =Profesion.get_all()
    return welcome_view.proyectos(proyectos,usuarios,profession)

@welcome_bp.route('/contacto')
def contacto():
    return welcome_view.contacto()

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>{% block title %} {% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="../static/img/favicon.png" rel="icon">
  <link href="../static/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="../static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="../static/vendor/aos/aos.css" rel="stylesheet">
  <link href="../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="../static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="../static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="../static/css/main.css" rel="stylesheet">

</head>

<body class="index-page">

  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
        <img src="../static/img/logo.png" alt="">
        <h1 class="sitename">Torres</h1> <span>.</span>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="/" class="{{ is_active('/inicio/') }}">Inicio</a></li>
          <li><a href="{{ url_for('inicio.nosotros') }}" class="{{ is_active('/inicio/nosotros') }}">Nosotros</a></li>
          <li><a href="{{ url_for('inicio.servicios') }}" class="{{ is_active('/inicio/servicios') }}">Servicios</a></li>
          <li><a href="{{ url_for('inicio.proyectos') }}" class="{{ is_active('/inicio/proyectos') }}">Proyectos</a></li>
          <li><a href="{{ url_for('inicio.contacto') }}" class="{{ is_active('/inicio/contacto') }}">Contacto</a></li>
          <button class="btn btn-outline-warning"><a href="/login/">Login</a></button>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>

  <main class="main">

    {% block content %}
    <!-- section -->
    {% endblock %}

  </main>

  <footer id="footer" class="footer dark-background">

    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-4 col-md-6 footer-about">
          <a href="index.html" class="logo d-flex align-items-center">
            <span class="sitename">KSTorres s.r.l.</span>
          </a>
          <div class="footer-contact pt-3">
            <p>Calle Federico Suaso, edificio alcazar, Nro 1885,</p>
            <p>La Paz - Bolivia</p>
            <p class="mt-3"><strong>Celular:</strong> <span>65675740</span></p>
            <p><strong>Email:</strong> <span>alejandro.rojas@kstorressrl.com</span></p>
          </div>
          <div class="social-links d-flex mt-4">
            <a href=""><i class="bi bi-twitter-x"></i></a>
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-3 col-md-3 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/nosotros">Nosotros</a></li>
            <li><a href="/servicios">Servicios</a></li>
            <li><a href="/proyectos">Proyectos</a></li>
            <li><a href="/contacto">Privacy policy</a></li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 footer-links">
            <img src="../static/img/logot.png" alt="" width="250">
            <ul>
                <h4>Empresa Constructora y maquinaria</h4>
            </ul>
            
          </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">KSTorres</strong> <span>Derechos Reservados</span></p>
      <div class="credits">
        Designed by <a href="#">CristianFlores</a>
      </div>
    </div>

  </footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="../static/vendor/php-email-form/validate.js"></script>
  <script src="../static/vendor/aos/aos.js"></script>
  <script src="../static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="../static/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
  <script src="../static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="../static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="../static/vendor/purecounter/purecounter_vanilla.js"></script>

  <!-- Main JS File -->
  <script src="../static/js/main.js"></script>

</body>

</html>

templates/layout_adm.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>T{% block title %} {% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='img/favicon.png') }}" rel="icon">
  <link href="{{ url_for('static',filename='img/favicon.png') }}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static',filename='assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/quill/quill.snow.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/quill/quill.bubble.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/remixicon/remixicon.css')}}" rel="stylesheet">
  <link href="{{url_for('static',filename='assets/vendor/simple-datatables/style.css')}}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{url_for('static',filename='assets/css/style.css')}}" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
        <img src="{{url_for('static',filename='img/logot.png')}}" alt="" width="90">
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-bell"></i>
            <span class="badge bg-primary badge-number">4</span>
          </a><!-- End Notification Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
            <li class="dropdown-header">
              You have 4 new notifications
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-exclamation-circle text-warning"></i>
              <div>
                <h4>Lorem Ipsum</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>30 min. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-x-circle text-danger"></i>
              <div>
                <h4>Atque rerum nesciunt</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>1 hr. ago</p>
              </div>
            </li>
          </ul><!-- End Notification Dropdown Items -->

        </li><!-- End Notification Nav -->
        
        
        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{{url_for('static',filename='img/team/testimonials-5.jpg')}}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2"> Adm  </span>
          </a><!-- End Profile Iamge Icon -->
          
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            {% for log in user_log %}
            <li class="dropdown-header">
              <h6>{{ log.nombre }} {{log.apellido}}</h6>
              <span></span>
            </li>
            {% endfor %}
            <li>
              <hr class="dropdown-divider">
            </li>
            

            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{{ url_for('login.vaciar') }}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->
        
        
      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" href="/proyectos">
          <i class="bi bi-grid"></i>
          <span>Poryectos</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-journal-text"></i><span>Forms</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{{ url_for('proyecto.create') }}" class="{{ is_active('/proyectos/create') }}">
              <i class="bi bi-circle"></i><span>Nuevo proyecto</span>
            </a>
          </li>
          <li>
            <a href="{{ url_for('usuario.create') }}" class="{{ is_active('/usuarios/create') }}">
              <i class="bi bi-circle"></i><span>Nuevo usuario</span>
            </a>
          </li>
          <li>
            <a href="{{ url_for('inventario.create') }}" class="{{ is_active('/inventarios/create') }}">
              <i class="bi bi-circle"></i><span>Nuevo material</span>
            </a>
          </li>
          <li>
            <a href="{{ url_for('factura.create') }}" class="{{ is_active('/facturas/create') }}">
              <i class="bi bi-circle"></i><span>Nuevo factura</span>
            </a>
          </li>
          <li>
            <a href="{{ url_for('login.create') }}" class="{{ is_active('/login/create') }}">
              <i class="bi bi-circle"></i><span>Asignar Username</span>
            </a>
          </li>
        </ul>
      </li><!-- End Forms Nav -->

      <li class="nav-item">
        <a class="nav-link" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-layout-text-window-reverse"></i><span>Tables</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-nav" class="nav-content collapse show" data-bs-parent="#sidebar-nav">
          <li>
            <a href="{{ url_for('usuario.index') }}" class="{{ is_active('/usuarios/') }}">
              <i class="bi bi-circle"></i><span>Usuarios</span>
            </a>
          </li>
          <li>
            <a href="{{ url_for('proyecto.detalles') }}" class="{{ is_active('/proyectos/detalle') }}">
              <i class="bi bi-circle"></i><span>Proyectos</span>
            </a>
          </li>
          <li>
            <a href="{{ url_for('inventario.index') }}" class="{{ is_active('/inventarios/') }}">
              <i class="bi bi-circle"></i><span>Material de Construcion</span>
            </a>
          </li>
        </ul>
      </li><!-- End Tables Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#icons-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-stack"></i><span>Facturas</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="icons-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{{ url_for('factura.index') }}" class="{{ is_active('/facturas/') }}">
              <i class="bi bi-circle"></i><span>Facturas</span>
            </a>
          </li>
        </ul>
      </li><!-- End Icons Nav -->

      <li class="nav-heading">Pages</li>

      <li class="nav-item">
        <a class="nav-link collapsed {{ is_active('/usuarios/user_profile') }}" href="{{ url_for('usuario.user_profile',id=4) }}">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li><!-- End Profile Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main">

    {% block content %}
    <!-- section -->
    {% endblock %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>KsTorres</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      Designed by <a href="{{ url_for('login.vaciar') }}">Cristian Flores</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{{url_for('static',filename='assets/vendor/apexcharts/apexcharts.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/chart.js/chart.umd.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/echarts/echarts.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/quill/quill.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/simple-datatables/simple-datatables.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/tinymce/tinymce.min.js')}}"></script>
  <script src="{{url_for('static',filename='assets/vendor/php-email-form/validate.js')}}"></script>

  <!-- Template Main JS File -->
  <script src="{{url_for('static',filename='assets/js/main.js')}}"></script>

</body>

</html>

templates/layout_login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>KSTorres | login</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="../static/img/favicon.png" rel="icon">
  <link href="../static/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="../static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="../static/vendor/aos/aos.css" rel="stylesheet">
  <link href="../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="../static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="../static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="../../static/css/main.css" rel="stylesheet">

</head>

<body class="index-page" >
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">
          <nav id="navmenu" class="navmenu">
            <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
          </nav>
        </div>
    </header>
  <main id="footer" class="footer dark-background">
    {% block content %}
    <!-- section -->
    {% endblock %}

  </main>

    <!-- Preloader -->
    <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="../static/vendor/php-email-form/validate.js"></script>
  <script src="../static/vendor/aos/aos.js"></script>
  <script src="../static/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="../static/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
  <script src="../static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="../static/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="../static/vendor/purecounter/purecounter_vanilla.js"></script>

  <!-- Main JS File -->
  <script src="../static/js/main.js"></script>

</body>

</html>