controllers/inventarios_controller.py
from flask import request,redirect,url_for,Blueprint
from datetime import datetime
from models.proyectos_model import Proyecto
from models.inventario_model import Inventario
from models.factura_model import Factura
from views import inventario_view

inventario_bp=Blueprint('inventario',__name__,url_prefix='/inventarios')

@inventario_bp.route('/')
def index():
    # recupera todo los registros de inventarios
    inventarios = Inventario.query.all()
    projects =Proyecto.query.all()
    return inventario_view.list(inventarios,projects)

@inventario_bp.route('/create',methods=['GET','POST'])
def create():
    if request.method == 'POST':
        material=request.form['material']
        cantidad=request.form['cantidad']
        unidad=request.form['unidad']
        costounit=request.form['costo']
        totals = request.form['total']
        id_proyecto = request.form['id_proyecto']
        nro_factura = request.form['factura']

        if costounit and not totals:
            total=int(costounit) * int(cantidad)
            costo_unit=costounit

        if totals and not costounit:
            costo_unit = int(totals) / int(cantidad)
            total=totals

        if costounit and totals:
            if int(totals) == int(costounit)*int(cantidad):
                costo_unit=costounit
                total=totals
            else:
                total=int(costounit)*int(cantidad)
                costo_unit=costounit

        inventarios = Inventario(material,cantidad,unidad,costo_unit,total,id_proyecto)
        inventarios.save()

        concepto = material
        monto = total
        cuenta = 0
        saldo = total
        fecha = datetime.now().date()
        if saldo == 0:
            deuda = 'cancelado'

        if saldo == monto:
            deuda = 'nuevo'
        
        facturas = Factura(id_proyecto,nro_factura,concepto,monto,cuenta,saldo,deuda,fecha)
        facturas.save()

        return redirect(url_for('inventario.index'))

    projects = Proyecto.query.filter_by(estado ='En Construsccion')
    return inventario_view.create(projects)

@inventario_bp.route('/edit/<int:id>',methods=['GET','POST'])
def edit(id):
    inventario = Inventario.get_by_id(id)
    if request.method=='POST':
        material=request.form['material']
        cantidad=request.form['cantidad']
        unidad=request.form['unidad']
        costo_unit=request.form['costo']
        total = int(costo_unit) * int(cantidad)
        id_proyecto = request.form['id_proyecto']

        # actualizar
        inventario.update(material=material,cantidad=cantidad,unidad=unidad,costo_unit=costo_unit,total=total,id_proyecto=id_proyecto)
        return redirect(url_for('inventario.index'))
    
    projects = Proyecto.get_all()
    return inventario_view.edit(inventario,projects)

@inventario_bp.route('/delete/<int:id>')
def delete(id):
    inventario=Inventario.get_by_id(id)
    inventario.delete()
    return redirect(url_for('inventario.index'))

views/inventario_view.py
from flask import render_template

def list(inventarios,projects):
    return render_template('inventarios/index.html',inventarios=inventarios,projects=projects)

def create(projects):
    # se requiere projects
    return render_template('inventarios/create.html',projects=projects)

def edit(inventario,projects):
    # se requiere inventario y proyectos
    return render_template('inventarios/edit.html',inventario=inventario,projects=projects)

templates/inventarios/create.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Registrar Inventario {% endblock %}

{% block content %}
<section class="section">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <img class="d-flex justify-content-center text-center py-4" src="{{url_for('static',filename='img/logot.png')}}" alt="" width="200">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Registrar Nuevo Material</h5>

                <!-- Multi Columns Form -->
                <form class="row g-3" method="POST" action="{{ url_for('inventario.create') }}">
                <div class="col-md-12">
                    <label for="" class="form-label">Material de Construccion</label>
                    <input type="text" class="form-control" name="material" required>
                </div>
                <div class="col-md-12">
                    <label for="" class="form-label">Cantidad</label>
                    <input type="number" class="form-control" name="cantidad"required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Unidad de medida de material</label>
                    <input type="text" class="form-control" name="unidad">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Precio unitario</label>
                    <input type="number" class="form-control" name="costo" min="0" step="0.01">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Total</label>
                    <input type="number" class="form-control" name="total" min="0" step="0.01">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Proyecto</label>
                    <select name="id_proyecto" id="" class="form-control" required>
                        <option value="">Seleccionar Proyecto</option>
                        {% for item in projects %}
                        <option value="{{ item.id }}">{{ item.proyecto }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Numero de Factura</label>
                    <input type="number" class="form-control" name="factura" min="0" step="0.01">
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-warning">Registrar</button>
                </div>
                </form><!-- End Multi Columns Form -->

            </div>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
  </section>
{% endblock %}

templates/inventarios/edit.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Editar Inventario {% endblock %}

{% block content %}
<section class="section">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <img class="d-flex justify-content-center text-center py-4" src="{{url_for('static',filename='img/logot.png')}}" alt="" width="200">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Editar inventario</h5>

                <!-- Multi Columns Form -->
                <form class="row g-3" method="POST" action="{{ url_for('inventario.edit',id=inventario.id) }}">
                <div class="col-md-12">
                    <label for="" class="form-label">Material de Construccion</label>
                    <input type="text" class="form-control" value="{{ inventario.material }}" name="material" required>
                </div>
                <div class="col-md-12">
                    <label for="" class="form-label">Cantidad</label>
                    <input type="number" class="form-control" value="{{ inventario.cantidad }}" name="cantidad" required>
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Unidad de medida de material</label>
                    <input type="text" class="form-control" value="{{ inventario.unidad }}" name="unidad">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Precio unitario</label>
                    <input type="number" class="form-control" value="{{ inventario.costo_unit }}" name="costo" min="0" step="0.01">
                </div>
                <div class="col-md-6">
                    <label for="" class="form-label">Pryecto</label>
                    <select name="id_proyecto" id="" class="form-control" required>
                        <option value="">Seleccionar Proyecto</option>
                        {% for item in projects %}
                        <option value="{{ item.id }}" {% if item.id == inventario.id_proyecto %} selected {% endif %}>{{ item.proyecto }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-warning">Modificar</button>
                </div>
                </form><!-- End Multi Columns Form -->

            </div>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>
  </section>
{% endblock %}

templates/inventarios/index.html
{% extends "layout_adm.html" %}
{% block title %} KSTorres | Inventarios {% endblock %}

{% block content %}
<div class="pagetitle">
    <h1>Inventarios</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Inventarios</a></li>
        <li class="breadcrumb-item">Tables</li>
        <li class="breadcrumb-item active">Data</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      <div class="col-lg-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Inventarios de materiales</h5>
                <!-- Table with stripped rows -->
                <table class="table datatable">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Proyecto</th>
                        <th>Material</th> 
                        <th>Cantidad</th>
                        <th>Unidad de medida</th>
                        <th>Costo unitario</th>
                        <th>Total</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in inventarios %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <td>{{ item.inventory.proyecto }}</td>
                        <td>{{ item.material }}</td>
                        <td>{{ item.cantidad }}</td>
                        <td>{{ item.unidad }}</td>
                        <td>Bs {{ item.costo_unit }}</td>
                        <td>Bs {{ item.total}}</td>
                        <td>
                        <a href="{{ url_for('inventario.edit',id=item.id) }}" class="btn btn-outline-warning"><i class="bi bi-pencil-square"></i></a>
                        </td>
                        <td>
                        <a href="{{ url_for('inventario.delete',id=item.id) }}" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <!-- End Table with stripped rows -->

            </div>
        </div>

      </div>
    </div>
  </section>
{% endblock %}